// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9dLTx_EbtRRkBnU2Ad_hfq6_M5nmd2Ns',
    appId: '1:641592510704:android:6780e10ce9c7c98d991a35',
    messagingSenderId: '641592510704',
    projectId: 'talenty-app',
    storageBucket: 'talenty-app.firebasestorage.app',
    // measurementId: 'G-HYLR3KGRNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9dLTx_EbtRRkBnU2Ad_hfq6_M5nmd2Ns',
    appId: '1:641592510704:android:6780e10ce9c7c98d991a35',
    messagingSenderId: '641592510704',
    projectId: 'talenty-app',
    storageBucket: 'talenty-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9dLTx_EbtRRkBnU2Ad_hfq6_M5nmd2Ns',
    appId: '1:641592510704:android:6780e10ce9c7c98d991a35',
    messagingSenderId: '641592510704',
    projectId: 'talenty-app',
    storageBucket: 'talenty-app.firebasestorage.app',
    // iosClientId:
    //     '816831984722-rnmhv8pt2rrq4b3tpi1i6o72rddqo074.apps.googleusercontent.com',
    // iosBundleId: 'com.example.flutterAntonxBoilerplate',
  );
}
